services:
  space-debris-tracker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_GPU_MEMORY_FRACTION=0.7
      - TF_CPP_MIN_LOG_LEVEL=1
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
