services:
  space-debris-tracker:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_GPU_MEMORY_FRACTION=0.8
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
      - ./scripts:/app/scripts
    restart: unless-stopped
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    depends_on:
      - redis
  redis:
    image: docker.io/library/redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
