services:
  space-debris-tracker:
    build:
      context: .
      dockerfile: Containerfile.cpu
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=1
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
      - ./scripts:/app/scripts
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: docker.io/library/redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
